### ISSUE TITLE
配置管理页面报错

### ISSUE THREAD

**Issue by yuedun** [cuo9958/node-config#3]
添加新配置的时候报错：
```
访问：/all/new
(node:17244) UnhandledPromiseRejectionWarning: Error: This
 socket is closed
    at Socket._writeGeneric (net.js:733:18)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at client_list.forEach.socket (E:\workspace\node-confi
g-master\lib\heart.js:77:27)
    at Array.forEach (<anonymous>)
    at Object.send (E:\workspace\node-config-master\lib\he
art.js:76:21)
    at Object.update (E:\workspace\node-config-master\lib\
data.js:110:15)
(node:17244) UnhandledPromiseRejectionWarning: Unhandled p
romise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by
rejecting a promise which was not handled with .catch(). (
rejection id: 10)
```

**Comment by cuo9958** [comment]
这个是从线上的仓库中拆的代码，可能有些遗漏。目前已经可以了。
